### ISSUE TITLE
Pass $res object to 'response' callback

### ISSUE THREAD

**Issue by KES777** [ap/Plack-Middleware-Rewrite#6]
This sounds very cool:

> Its primary purpose is rewriting paths, but almost anything is possible very easily.

But:

> Just as in `request`, the PSGI environment is passed as first and only argument.

From now I can not rewrite response code based on response body/headers

It will be cool if you pass whole `$res` array as second parameter too

**Comment by ap** [comment]
D’oh.

But I’m not going to do that. Not just that, anyway. I’m not happy with the `response` interface as a whole. I’ll have a think on how it should look.

**Comment by KES777** [comment]
I use 'Rewrite' as before/after hook for logging queries and response code/headers for my app.

Maybe create new module with request/response hooks and name it P::M::SniffDialog, for example?

**Comment by ap** [comment]
> I use 'Rewrite' as before/after hook for logging queries and response code/headers for my app.

Sure, sounds just like a job for it.

> Maybe create new module with request/response hooks and name it P::M::SniffDialog, for example?

Err… what… why?

**Comment by ap** [comment]
Sorry this fell through the cracks so badly! It took me a while to figure out how to fit this into the API (embarrassingly obvious in retrospect), and then I still took forever to finish it up. Hopefully it’s still useful.

Share and enjoy. 😊
